### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by bondz** [bonniee/react-starter#1]
I'm not sure what [this](/bonniee/react-starter/blob/22151093313412aed774c198e8398c40a0969c49/webpack.config.js#L13) line matches. Would it not match `.j` files and `.js` files. Please clarify.

**Comment by smbossco** [comment]
that's exactly right, it will match .j or .js at the end of a string

**Comment by bondz** [comment]
Oh, okay, thanks for clarifying. I could save my files with a .j extension.
